apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes: 
  - ReadWriteOnce
  storageClassName: roboshop-ebs  # this is from StorageClass 
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-ebs-dynamic
  labels:
    purpose: ebs-dynamic-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers: 
  - name: nginx
    image: nginx
    volumeMounts: 
    - name: persistent-storage # this is same as volumes name
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage # this is same as volumeMount name
    persistentVolumeClaim:  
      claimName: ebs-dynamic # PVC Name
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic
  labels:
    purpose: ebs-dynamic-demo 
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port