apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: roboshop-efs
  resources: 
    request:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic-test
  labels:
    purpose: efs-dynamic-demo 
    project: roboshop
spec:
  containers:
  - name: efs-dynamic-nginx
    image: nginx
    volumeMounts:
    - name: persistent-volumes-efs
      mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-volumes-efs
      PersistentVolumeClaim:
        claimName: efs-dynamic
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic-demo 
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
